### ISSUE TITLE
Support for ANSIBLE_CONFIG

### ISSUE THREAD

**Issue by bzlowrance** [rundeck-plugins/ansible-plugin#100]
Please add an enhancement which will allow for different ANSIBLE_CONFIG files to be defined at the project level.
E.G. project.ansible-config=/etc/ansible/project1.cfg

**Comment by yassineazzouz** [comment]
Hi @bzlowrance ,
This will be planned for next release.
Thanks,

**Comment by martinbydefault** [comment]
It would be even better and more general to add an option to select in each project the location of the ansible project, as discused in #47 .  
Also, if the `ansible.cfg` file has relative paths (used a lot in a collaborative projects) even if you set the `ANSIBLE_CONFIG` var, you are still going to have problems because the paths inside the config file are going to being expanded against the PWD you are executing the playbook.  
Here is a issue in the ansible repo asking for changing this: https://github.com/ansible/ansible/issues/5185

**Comment by ioannisas** [comment]
Any update on this?

Also it would be great if there was an option to set working directory per job instead of project - or just the ansible  configuration file path.
Jobs inside the same project may need different configuration.
