### ISSUE TITLE
Ansible runs once for each host

### ISSUE THREAD

**Issue by jseynaev-cisco** [rundeck-plugins/ansible-plugin#286]
Hello,

This is just a question, but when running an Ansible Playnbook Job in Rundeck, it looks like every host is a seperate run of the playbook with that host only.
Is it possible to have the Playbook run for all hosts selected in the same run ? 

I'm asking, because the output in Rundeck now is in a dropdown where you need to drill in for each host, which is a bit of a pain when there's a lot of hosts.  If all hosts were in the same run, the output would be condensed (and more like the cli ansible) into a single output for all.

Regards,
Jan.

**Comment by benhwebster** [comment]
I believe it may be because you are using the node playbook step (possibly inline as well) if you switch to using the workflow version it should put all nodes in a single run.

[This webinar](https://www.youtube.com/watch?v=PuLtUQLT4fM) from the rundeck team shows some of the differences between the ways of executing ansible jobs from rundeck.

**Comment by jseynaev-cisco** [comment]
Ha! That is it indeed ... so easy, thx a lot for pointing me to that video
