### ISSUE TITLE
Add @yassineazzouz as a collaborator

### ISSUE THREAD

**Issue by frozenice** [rundeck-plugins/ansible-plugin#44]
Hey @yassineazzouz, I invited you as a collaborator to this repo, as you showed high interest in this project and did quite a bit of work already (during my vacation, from which I'm back now, and earlier).

I hope you will continue to contribute to this repo. Feel free to triage /  issues and PRs!

I guess I'll need to add a CONTRIBUTING file to explain the build and release steps (basically IntelliJ + Gradle) and my idea of the issue labels etc., if it isn't clear.

I hope you accept. ;)

**Comment by yassineazzouz** [comment]
Thank you so much for the invitation @frozenice , I gladly accept and I'm very happy to contribute, and keep improving the ansible rundeck plugin. I managed to get few working hours weekly to support the development and improvement of this project, since we are relying extensively on it and we really enjoy using it. 
I think I'm familiar with most of the development, build, testing and releasing process, but it will be great if you could share with me more details.

Thanks,

**Comment by frozenice** [comment]
Awesome news, happy to have you on board! I added a first version of [the CONTRIBUTING file](CONTRIBUTING.md) - to be fleshed out. I hope I got everything covered, tell me if you run into any problems!
