### ISSUE TITLE
Failed to create parent directory '/workspace/rundeck-ansible-plugin/.gradle' when creating directory '/workspace/rundeck-ansible-plugin/.gradle/2.14.1/taskArtifacts

### ISSUE THREAD

**Issue by amishra123** [rundeck-plugins/ansible-plugin#56]
hi I am building with gradle.

gradle tasks

FAILURE: Build failed with an exception.
- What went wrong:
  Could not create service of type TaskArtifactStateCacheAccess using TaskExecutionServices.createCacheAccess().
  
  > Failed to create parent directory '/workspace/rundeck-ansible-plugin/.gradle' when creating directory '/workspace/rundeck-ansible-plugin/.gradle/2.14.1/taskArtifacts'
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.429 secs 

Can anyone tell whats the issue here?

**Comment by frozenice** [comment]
Looks like it can't create the `.gradle` directory inside your workspace. Could be a permission issue. Try running with `--info` or `--debug` to see if it tells you the exact error.

Also try using the included [gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html), it's a different version (2.5 instead of your 2.14.1).

**Comment by ashishkumar4029** [comment]
The same problem happened with me.
What I did was this.
### sudo gradle
It solved the problem.
Hope it works with you.

**Comment by kbigdelysh** [comment]
I resolved the same issue by running this command: **File > Invalidate Caches / Restart ...**
