### ISSUE TITLE
Support for context editor for Ansible PlayBook

### ISSUE THREAD

**Issue by QUASARFREAK** [rundeck-plugins/ansible-plugin#68]
It would be awesome to have a text area to create or edit an ansible playbook, right now we can only select the path were a previously ansible playbook had to be stored.

**Comment by yassineazzouz** [comment]
Hi @QUASARFREAK ,

Sounds like a nice suggestion, but I don't think this can be easily done since ansible uses the path of the playbook to find out the project it is associated with: for instance if the folder containing the playbook contains a "roles" or "group_vars" folder they will be defined in your play. 
The problem when creating playbooks is that it will be limited to simple modules, without any group_vars or roles .... than can be used, in that case it will be just like using  a sequence of module jobs, right ?

**Comment by DerekTBrown** [comment]
This feature was added in https://github.com/Batix/rundeck-ansible-plugin/pull/128
