### ISSUE TITLE
New Project - Resource model ssh key path button etc?

### ISSUE THREAD

**Issue by pentiumoverdrive** [rundeck-plugins/ansible-plugin#76]
Maybe I'm confused, but all ansible dialogues except for when you create resource model has an "open" button which lets you select your ssh keys from path.

Also resource model dialogue does not support privilege escalation password stored in key storage either which forces me to enter this password here, but not in the other dialogues.

**Comment by pentiumoverdrive** [comment]
From what I understand - you can only use ssh key storage for everything EXCEPT when importing the nodes? I still need to have my private ssh-key file stored on the server, besides rundeck key storage?

**Comment by yassineazzouz** [comment]
Hi @pentiumoverdrive ,

Unfortunately that's a limitation in rundeck, you can not access the key storage in the resource model since there is no execution context associated with it. The reason for this is that typical resource models like xml files does not need accessing target hosts to gather resources, so the rundeck API for the resource model does not provide a way to read the key storage.

Thanks,

**Comment by pentiumoverdrive** [comment]
Ok, thanks, Now I understand the limitation :)

**Comment by jarosite** [comment]
Hi @yassineazzouz,
if resource model is designed to be a simple file, why ansible plugin can not use inventory file for this purposes? Because right now, key storage feature is useless for this plugin.

**Comment by DerekTBrown** [comment]
@jarosite because that is not exposed to the plugin API.
